const BORDERS = [
  ["ARG", "BRA"],
  ["ARG", "BOL", "BRA"],
  ["SEN"],
  ["ERI", "ETH", "SOM"],
  [],
  [],
  ["ARM", "AZE", "RUS", "TUR"],
  ["CAN", "MEX"],
  ["GTM", "MEX"],
  [],
  ["ISR", "SYR"],
  ["IRQ", "JOR", "KWT", "OMN", "QAT", "ARE", "YEM"],
  ["COL", "PER"],
  [],
  ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"],
  ["COD", "KEN", "RWA", "SSD", "TZA"],
  ["SAU"],
  ["IDN"],
  ["CHN", "RUS"],
  ["ARG", "BOL", "PER"],
  ["GIN", "CIV", "SLE"],
  [],
  [],
  [],
  [],
  [],
  [],
  ["BOL", "BRA", "CHL", "PRY", "URY"],
  ["BEN", "BFA", "GHA"],
  ["CZE", "DEU", "HUN", "ITA", "LIE", "SVK", "SVN", "CHE"],
  [],
  [],
  ["DZA", "ESH", "ESP"],
  [],
  [],
  [],
  ["DZA", "MLI", "SEN", "ESH"],
  ["BLR", "HUN", "MDA", "POL", "ROU", "RUS", "SVK"],
  ["AFG", "BTN", "MMR", "HKG", "IND", "KAZ", "NPL", "PRK", "KGZ", "LAO", "MAC", "MNG", "PAK", "RUS", "TJK", "VNM"],
  ["ZAF"],
  [],
  ["AGO", "BDI", "CAF", "COG", "RWA", "SSD", "TZA", "UGA", "ZMB"],
  ["AZE", "BLR", "CHN", "EST", "FIN", "GEO", "KAZ", "PRK", "LVA", "LTU", "MNG", "NOR", "POL", "UKR"],
  ["MMR", "IND"],
  ["BWA", "LSO", "MOZ", "NAM", "SWZ", "ZWE"],
  [],
  ["BLZ", "SLV", "HND", "MEX"],
  [],
  [],
  ["EGY", "JOR", "LBN", "PSE", "SYR"],
  ["BRA", "SUR", "VEN"],
  [],
  ["BIH", "HUN", "MNE", "SRB", "SVN"],
  [],
  [],
  ["MAF"],
  ["AGO", "BWA", "ZAF", "ZMB"],
  [],
  ["ESP"],
  ["GMB", "GIN", "GNB", "MLI", "MRT"],
  [],
  ["SAU", "ARE", "YEM"],
  ["IRQ", "SAU"],
  [],
  [],
  [],
  ["IRL"],
  ["GTM", "SLV", "NIC"],
  [],
  ["LAO", "THA", "VNM"],
  ["ALB", "BGR", "GRC", "UNK", "SRB"],
  ["AFG", "ARM", "AZE", "IRQ", "PAK", "TUR", "TKM"],
  ["COL", "CRI"],
  [],
  ["FRA", "ESP"],
  ["COD", "RWA", "TZA"],
  [],
  [],
  [],
  ["ALB", "MKD", "MNE", "SRB"],
  ["BEN", "CMR", "TCD", "NER"],
  ["BLR", "CZE", "DEU", "LTU", "RUS", "SVK", "UKR"],
  [],
  [],
  ["DJI", "ERI", "KEN", "SOM", "SSD", "SDN"],
  ["AUT", "BEL", "CZE", "DNK", "FRA", "LUX", "NLD", "POL", "CHE"],
  ["ARM", "GEO", "IRN", "RUS", "TUR"],
  ["BEL", "DEU"],
  ["AND", "BEL", "DEU", "ITA", "LUX", "MCO", "ESP", "CHE"],
  ["CHN", "IND"],
  [],
  [],
  ["BGD", "BTN", "MMR", "CHN", "NPL", "PAK"],
  ["CHN", "KAZ", "TJK", "UZB"],
  ["CAF", "COD", "ETH", "KEN", "SDN", "UGA"],
  ["IRN", "JOR", "KWT", "SAU", "SYR", "TUR"],
  ["AUT", "FRA", "SMR", "SVN", "CHE", "VAT"],
  [],
  ["CHN", "IND"],
  [],
  ["FIN", "SWE", "RUS"],
  ["BLR", "LVA", "POL", "RUS"],
  ["ETH", "SOM", "SSD", "TZA", "UGA"],
  [],
  ["FIN", "NOR"],
  [],
  ["CMR", "COG", "GNQ"],
  ["CHN"],
  [],
  ["BDI", "COD", "TZA", "UGA"],
  ["IRQ", "ISR", "JOR", "LBN", "TUR"],
  ["USA"],
  ["TUN", "LBY", "NER", "ESH", "MRT", "MLI", "MAR"],
  [],
  ["DZA", "MRT", "MAR"],
  [],
  ["NAM", "ZAF", "ZMB", "ZWE"],
  ["CHN", "KGZ", "RUS", "TKM", "UZB"],
  ["BRA", "COL", "GUY"],
  [],
  ["CAF", "TCD", "EGY", "ERI", "ETH", "LBY", "SSD"],
  [],
  ["AUT", "CZE", "HUN", "POL", "UKR"],
  [],
  [],
  [],
  ["BLR", "EST", "LTU", "RUS"],
  [],
  [],
  ["IRN", "PAK", "TKM", "UZB", "TJK", "CHN"],
  ["BIH", "BGR", "HRV", "HUN", "UNK", "MKD", "MNE", "ROU"],
  ["AFG", "CHN", "KGZ", "UZB"],
  [],
  [],
  ["DJI", "ETH", "SDN"],
  ["DZA", "BFA", "GIN", "CIV", "MRT", "NER", "SEN"],
  ["DOM"],
  [],
  ["HRV", "MNE", "SRB"],
  ["ITA"],
  ["BFA", "NER", "NGA", "TGO"],
  [],
  [],
  ["ARG", "BRA", "CHL", "PRY", "PER"],
  [],
  [],
  [],
  ["ALB", "BGR", "TUR", "MKD"],
  ["BOL", "BRA", "CHL", "COL", "ECU"],
  ["BRA", "GUF", "GUY"],
  [],
  ["DZA", "BEN", "BFA", "TCD", "LBY", "MLI", "NGA"],
  ["MMR", "KHM", "LAO", "MYS"],
  [],
  ["CHN", "KOR", "RUS"],
  ["BFA", "GHA", "GIN", "LBR", "MLI"],
  ["OMN", "SAU"],
  [],
  ["AZE", "GEO", "IRN", "TUR"],
  ["AFG", "CHN", "IND", "IRN"],
  [],
  ["MOZ", "TZA", "ZMB"],
  ["GBR"],
  [],
  ["AUT", "DEU", "POL", "SVK"],
  ["BGD", "CHN", "IND", "LAO", "THA"],
  [],
  ["BGR", "HUN", "MDA", "SRB", "UKR"],
  ["HTI"],
  ["CMR", "GAB"],
  ["BFA", "CIV", "TGO"],
  [],
  ["ARM", "AZE", "BGR", "GEO", "GRC", "IRN", "IRQ", "SYR"],
  ["ISR", "LBY", "PSE", "SDN"],
  ["MWI", "ZAF", "SWZ", "TZA", "ZMB", "ZWE"],
  [],
  ["FRA", "DEU", "LUX", "NLD"],
  ["AUT", "HRV", "ITA", "HUN"],
  ["AUT", "HRV", "ROU", "SRB", "SVK", "SVN", "UKR"],
  ["OMN", "SAU"],
  ["MNE", "GRC", "MKD", "UNK"],
  [],
  [],
  ["ITA"],
  ["ROU", "UKR"],
  ["LVA", "RUS"],
  [],
  [],
  ["LVA", "LTU", "POL", "RUS", "UKR"],
  ["IND"],
  ["GTM", "HND"],
  [],
  [],
  ["CRI", "HND"],
  ["DJI", "ETH", "KEN"],
  [],
  [],
  ["ISR", "EGY", "JOR"],
  ["AFG", "IRN", "KAZ", "UZB"],
  ["BEN", "CIV", "GHA", "MLI", "NER", "TGO"],
  ["NIC", "PAN"],
  ["KHM", "CHN", "LAO"],
  ["CAF", "TCD", "COG", "GNQ", "GAB", "NGA"],
  ["BRA", "SUR"],
  ["MOZ", "ZAF"],
  ["AGO", "BWA", "COD", "MWI", "MOZ", "NAM", "TZA", "ZWE"],
  ["AUT", "CHE"],
  ["ALB", "BIH", "HRV", "UNK", "SRB"],
  [],
  ["AFG", "KAZ", "KGZ", "TJK", "TKM"],
  ["CMR", "CAF", "LBY", "NER", "NGA", "SDN"],
  [],
  ["DEU"],
  [],
  [],
  ["AUT", "FRA", "ITA", "LIE", "DEU"],
  ["CHN"],
  ["GRC", "MKD", "ROU", "SRB", "TUR"],
  ["IRQ", "ISR", "PSE", "SAU", "SYR"],
  ["AGO", "CMR", "CAF", "COD", "GAB"],
  ["MMR", "KHM", "CHN", "THA", "VNM"],
  [],
  ["PRK"],
  ["DZA", "LBY"],
  ["NOR", "SWE", "RUS"],
  ["BWA", "MOZ", "ZAF", "ZMB"],
  [],
  [],
  ["FRA"],
  ["COG", "COD", "ZMB", "NAM"],
  ["BRN", "IDN", "THA"],
  ["BEL", "FRA", "DEU"],
  ["CIV", "GNB", "LBR", "MLI", "SEN", "SLE"],
  ["DZA", "TCD", "EGY", "NER", "SDN", "TUN"],
  ["AND", "FRA", "GIB", "PRT", "MAR"],
  ["TLS", "MYS", "PNG"],
  [],
  ["MYS"],
  ["BLZ", "GTM", "USA"],
  [],
  ["GIN", "LBR"],
  ["CMR", "TCD", "COD", "COG", "SSD", "SDN"],
  [],
  ["BRA", "ECU", "PAN", "PER", "VEN"],
  ["IDN"],
  [],
  ["ESP"],
  ["GIN", "SEN"],
  ["SXM"],
  ["BDI", "COD", "KEN", "MWI", "MOZ", "RWA", "UGA", "ZMB"]
];