const CAPITALS = [
	"Montevideo", 
	"Asunción", 
	"Banjul", 
	"Djibouti", 
	"Fort-de-France", 
	"Hagåtña", 
	"Tbilisi", 
	"Washington, D.C.", 
	"Belmopan", 
	"Port Louis", 
	"Beirut", 
	"Riyadh", 
	"Quito", 
	"Majuro", 
	"Brasília", 
	"Kampala", 
	"Doha", 
	"Dili", 
	"Ulan Bator", 
	"Santiago", 
	"Monrovia", 
	"Yaren", 
	"Saint-Denis", 
	"Plymouth", 
	"Taipei", 
	"undefined", 
	"Saint-Pierre", 
	"Buenos Aires", 
	"Lomé", 
	"Vienna", 
	"St. George's", 
	"Tórshavn", 
	"Rabat", 
	"The Valley", 
	"Ngerulmud", 
	"Saipan", 
	"Nouakchott", 
	"Kyiv", 
	"Beijing", 
	"Maseru", 
	"Nicosia", 
	"Kinshasa", 
	"Moscow", 
	"Dhaka", 
	"Pretoria,Bloemfontein,Cape Town", 
	"Willemstad", 
	"Guatemala City", 
	"San Juan", 
	"Saint John's", 
	"Jerusalem", 
	"Georgetown", 
	"George Town", 
	"Zagreb", 
	"Reykjavik", 
	"Kralendijk", 
	"Philipsburg", 
	"Windhoek", 
	"Roseau", 
	"Gibraltar", 
	"Dakar", 
	"Basseterre", 
	"Muscat", 
	"Kuwait City", 
	"Mariehamn", 
	"Charlotte Amalie", 
	"undefined", 
	"London", 
	"Tegucigalpa", 
	"King Edward Point", 
	"Phnom Penh", 
	"Skopje", 
	"Tehran", 
	"Panama City", 
	"Avarua", 
	"Andorra la Vella", 
	"Gitega", 
	"Port of Spain", 
	"Moroni", 
	"Port-aux-Français", 
	"Pristina", 
	"Abuja", 
	"Warsaw", 
	"Alofi", 
	"Nouméa", 
	"Addis Ababa", 
	"Berlin", 
	"Baku", 
	"Amsterdam", 
	"Paris", 
	"Kathmandu", 
	"Bridgetown", 
	"Saint Helier", 
	"New Delhi", 
	"Bishkek", 
	"Juba", 
	"Baghdad", 
	"Rome", 
	"Havana", 
	"Thimphu", 
	"Nassau", 
	"Oslo", 
	"Vilnius", 
	"Nairobi", 
	"Adamstown", 
	"Stockholm", 
	"Basse-Terre", 
	"Libreville", 
	"undefined", 
	"St. Peter Port", 
	"Kigali", 
	"Damascus", 
	"Ottawa", 
	"Algiers", 
	"Diego Garcia", 
	"El Aaiún", 
	"Douglas", 
	"Gaborone", 
	"Nur-Sultan", 
	"Caracas", 
	"Papeetē", 
	"Khartoum", 
	"Mata-Utu", 
	"Bratislava", 
	"Gustavia", 
	"Flying Fish Cove", 
	"Honiara", 
	"Riga", 
	"Road Town", 
	"Kingston", 
	"Kabul", 
	"Belgrade", 
	"Dushanbe", 
	"Nuku'alofa", 
	"South Tarawa", 
	"Asmara", 
	"Bamako", 
	"Port-au-Prince", 
	"Port Vila", 
	"Sarajevo", 
	"Vatican City", 
	"Porto-Novo", 
	"Longyearbyen", 
	"Apia", 
	"Sucre", 
	"Antananarivo", 
	"São Tomé", 
	"Manama", 
	"Athens", 
	"Lima", 
	"Paramaribo", 
	"Pago Pago", 
	"Niamey", 
	"Bangkok", 
	"Funafuti", 
	"Pyongyang", 
	"Yamoussoukro", 
	"Sana'a", 
	"Wellington", 
	"Yerevan", 
	"Islamabad", 
	"Fakaofo", 
	"Lilongwe", 
	"Dublin", 
	"Manila", 
	"Prague", 
	"Naypyidaw", 
	"West Island", 
	"Bucharest", 
	"Santo Domingo", 
	"Malabo", 
	"Accra", 
	"Valletta", 
	"Ankara", 
	"Cairo", 
	"Maputo", 
	"Mamoudzou", 
	"Brussels", 
	"Ljubljana", 
	"Budapest", 
	"Abu Dhabi", 
	"Tirana", 
	"undefined", 
	"Suva", 
	"City of San Marino", 
	"Chișinău", 
	"Tallinn", 
	"Kingstown", 
	"Washington DC", 
	"Minsk", 
	"Sri Jayawardenepura Kotte", 
	"San Salvador", 
	"Canberra", 
	"Hamilton", 
	"Managua", 
	"Mogadishu", 
	"Cockburn Town", 
	"Palikir", 
	"Ramallah", 
	"Ashgabat", 
	"Ouagadougou", 
	"San José", 
	"Hanoi", 
	"Yaoundé", 
	"Cayenne", 
	"Mbabane", 
	"Lusaka", 
	"Vaduz", 
	"Podgorica", 
	"Castries", 
	"Tashkent", 
	"N'Djamena", 
	"Oranjestad", 
	"Copenhagen", 
	"Tokyo", 
	"Praia", 
	"Bern", 
	"City of Victoria", 
	"Sofia", 
	"Amman", 
	"Brazzaville", 
	"Vientiane", 
	"Kingston", 
	"Seoul", 
	"Tunis", 
	"Helsinki", 
	"Harare", 
	"Malé", 
	"Singapore", 
	"Monaco", 
	"Luanda", 
	"Kuala Lumpur", 
	"Luxembourg", 
	"Conakry", 
	"Tripoli", 
	"Madrid", 
	"Jakarta", 
	"Victoria", 
	"Bandar Seri Begawan", 
	"Mexico City", 
	"Jamestown", 
	"Freetown", 
	"Bangui", 
	"Nuuk", 
	"Bogotá", 
	"Port Moresby", 
	"Stanley", 
	"Lisbon", 
	"Bissau", 
	"Marigot", 
	"Dodoma"
];
